### ISSUE TITLE
[240902~240908] SW Expert Academy - 팩토리얼과 최대공약수

### ISSUE THREAD

**Issue by hadevyi** [SSAFYnity/Job-Preparation-Challenge-2nd#7]
### 문제 개요

- 사이트 : SW Expert Academy
- 제목 : 7466. 팩토리얼과 최대공약수
- 링크 : https://swexpertacademy.com/main/code/problem/problemDetail.do?problemLevel=4&contestProbId=AWnghFyq9eMDFAQU&categoryId=AWnghFyq9eMDFAQU&categoryType=CODE&problemTitle=&orderBy=PASS_RATE&selectCodeLang=ALL&select-1=4&pageSize=10&pageIndex=10

**Comment by yjeum** [comment]
@hadevyi
제출 가능 언어가 C, C++, JAVA만 가능한 것 같습니다.
확인부탁드립니다!

**Comment by hadevyi** [comment]
> @hadevyi 제출 가능 언어가 C, C++, JAVA만 가능한 것 같습니다. 확인부탁드립니다!

감사합니다 :) 이번 출제때 확인한다 했는데 착오가 있었나봅니다.
차기 문제 출제 때는 고려하겠습니다!
